name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            git config --global --add safe.directory /home/ubuntu/app/todo-app
            cd /home/ubuntu/app/todo-app

            git pull origin master

            npm install

            
            rm -rf .next
            npm run build || exit 1

            pm2 reload todo-app

            pm2 save